apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: demo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
  namespace: demo
spec:
  serviceName: mongodb-service
  replicas: 3
  selector:
    matchLabels:
      role: mongo
      environment: test
      replicaset: MainRepSet
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        replicaset: MainRepSet
    spec:
      containers:
      - name: mongod-container
        image: mongo:3.6
        args:
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "MainRepSet"
        - "--auth"
        - "--clusterAuthMode"
        - "x509"
        - "--sslMode"
        - "requireSSL"
        - "--sslCAFile"
        - "/var/secrets/shared-bootstrap-data/tls.ca"
        - "--sslPEMKeyFile"
        - "/var/secrets/shared-bootstrap-data/tls.pem"
        - "--setParameter"
        - "authenticationMechanisms=SCRAM-SHA-1"
        env:
        - name: "MONGO_INITDB_ROOT_USERNAME"
          value: "root"
        - name: "MONGO_INITDB_ROOT_PASSWORD"
          value: "password"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: shared-bootstrap-data
          mountPath: /var/secrets/shared-bootstrap-data
        - name: mongodb-persistent-storage-claim
          mountPath: /data/db
        securityContext:
          runAsUser: 0
      volumes:
      - name: shared-bootstrap-data
        secret:
          secretName: shared-bootstrap-data
       # defaultMode: 511 #ocatl bits: 700
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
