apiVersion: v1
kind: Namespace
metadata:
  name: demo
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mongodb-replicaset
  name: my-release-mongodb-replicaset-mongodb
  namespace: demo
data:
  mongod.conf: |
    null
---
# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-gvr
  namespace: demo
spec:
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: mongo
  name: mgo-quickstart222
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  serviceName: mongo-gvr
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - args:
        - --auth
        - --config=/data/configdb/mongod.conf
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "pass"
        image: mongo:3.4
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
        - containerPort: 27017
          name: db
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db
          name: data
        - mountPath: /data/configdb
          name: configdir
      volumes:
      - name: configdir
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
      storageClassName: standard

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: demo
  labels:
    name: mongo
spec:
  ports:
    - port: 3306
  selector:
    name: mongo
