apiVersion: v1
items:
- apiVersion: v1
  data:
    password: cGFzcw==
    user: cm9vdA==
  kind: Secret
  metadata:
    creationTimestamp: 2018-06-11T07:26:05Z
    labels:
      app: mongodb-replicaset
      chart: mongodb-replicaset-3.4.1
      heritage: Tiller
      release: my-release
    name: my-release-mongodb-replicaset-admin
    namespace: demo
    resourceVersion: "14218"
    selfLink: /api/v1/namespaces/demo/secrets/my-release-mongodb-replicaset-admin
    uid: b36ce8e1-6d48-11e8-b260-0800272a2332
  type: Opaque
- apiVersion: v1
  data:
    key.txt: YXNkYXNkYXNkYXNkYXNkYXNk
  kind: Secret
  metadata:
    creationTimestamp: 2018-06-11T07:26:05Z
    labels:
      app: mongodb-replicaset
      chart: mongodb-replicaset-3.4.1
      heritage: Tiller
      release: my-release
    name: my-release-mongodb-replicaset-keyfile
    namespace: demo
    resourceVersion: "14220"
    selfLink: /api/v1/namespaces/demo/secrets/my-release-mongodb-replicaset-keyfile
    uid: b3779baa-6d48-11e8-b260-0800272a2332
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
