apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: 2018-07-05T12:05:48Z
  generation: 1
  labels:
    app: mongodb-replicaset
  name: my-release-mongodb-replicaset
  namespace: demo
  resourceVersion: "4247"
  selfLink: /apis/apps/v1/namespaces/demo/statefulsets/my-release-mongodb-replicaset
  uid: c0d116af-804b-11e8-8799-0800275310ae
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb-replicaset
  serviceName: my-release-mongodb-replicaset
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb-replicaset
    spec:
      containers:
      - args:
        - --config=/data/configdb/mongod.conf
        - --dbpath=/data/db
        - --replSet=rs0
        - --port=27017
        - --bind_ip=0.0.0.0
        - --auth
        - --keyFile=/data/configdb/key.txt
        command:
        - mongod
        image: maruftuhin/mongo:3.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mongodb-replicaset
        ports:
        - containerPort: 27017
          name: peer
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: datadir
        - mountPath: /data/configdb
          name: configdir
        - mountPath: /work-dir
          name: workdir
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --work-dir=/work-dir
        image: maruftuhin/mongo-init
        imagePullPolicy: Always
        name: install
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /work-dir
          name: workdir
        - mountPath: /configdb-readonly
          name: config
        - mountPath: /data/configdb
          name: configdir
        - mountPath: /keydir-readonly
          name: keydir
      - args:
        - -on-start=/work-dir/on-start.sh
        - -service=my-release-mongodb-replicaset
        command:
        - /work-dir/peer-finder
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: REPLICA_SET
          value: rs0
        - name: AUTH
          value: "true"
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: user
              name: my-release-mongodb-replicaset-admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: my-release-mongodb-replicaset-admin
        image: maruftuhin/mongo:3.6
        imagePullPolicy: Always
        name: bootstrap
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /work-dir
          name: workdir
        - mountPath: /data/configdb
          name: configdir
        - mountPath: /data/db
          name: datadir
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: my-release-mongodb-replicaset-mongodb
        name: config
      - name: keydir
        secret:
          defaultMode: 256
          secretName: my-release-mongodb-replicaset-keyfile
      - emptyDir: {}
        name: workdir
      - emptyDir: {}
        name: configdir
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: my-release-mongodb-replicaset-669f8df9db
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: my-release-mongodb-replicaset-669f8df9db
