apiVersion: v1
kind: Secret
data:
  password: cGFzcw==
  user: cm9vdA==
metadata:
  labels:
    app: mongodb-replicaset
  name: my-release-mongodb-replicaset-admin
  namespace: demo
type: Opaque
---
apiVersion: v1
data:
  key.txt: YXNkYXNkYXNkYXNkYXNkYXNk
kind: Secret
metadata:
  labels:
    app: mongodb-replicaset
  name: my-release-mongodb-replicaset-keyfile
  namespace: demo
type: Opaque
